### ISSUE TITLE
No '_ctx' column, also please add the 'region_name' support in openstack.spc

### ISSUE THREAD

**Issue by zhujian0805** [ernw/steampipe-plugin-openstack#3]
Hi, thanks for the new openstack plugin, now I'm using/testing it:
1. can we add the support for 'region_name' in the openstack.spc? If users have multiple regions, so we can add mulitple connections for multiple regions, instead using environment variables, I need to export the OS_REGION_NAME every time on the CLI.
2. I don't see the '_ctx' column in the tables, can it be added to all tables? it's useful when i need to know the region by using the _ctx column.
thanks you!

**Comment by gdebus** [comment]
Hi @zhujian0805,

thank you for the issue! Following information regarding your mentioned requests:

1. Since the [`AuthOptions`](https://pkg.go.dev/github.com/gophercloud/gophercloud#AuthOptions) of Gophercloud does not support the `region_name` configuration parameter, support for the parameter has not yet been implemented. _But_ the option will be implemented in the next release of the OpenStack steampipe plugin.
2. `_ctx` column is already included in every table as the last column. Please check, if the column is present for you.

**Comment by gdebus** [comment]
Fixed in 11183caaafdee464093108551c50351dd84a5e2e. @zhujian0805 if you have any further feature or table requests, please let me know by opening an issue.

**Comment by sven-ernw** [comment]
Released with [v0.0.3](https://github.com/ernw/steampipe-plugin-openstack/releases/tag/v0.0.3).
